In [4]:
!pwd

/home/saek/projects/python_kings


In [5]:
import numpy as np

In [7]:
weight = [67, 34, 99, 116, 85]
height = [145, 89, 180, 160, 185]

In [9]:
bmi = weight / (height/100) ** 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [14]:
np_height = np.array(height)

In [15]:
type(np_height)

numpy.ndarray

In [13]:
np_weight = np.array(weight)

In [16]:
np_weight

array([ 67,  34,  99, 116,  85])

In [17]:
np_bmi = np_weight / (np_height/100) ** 2

In [18]:
np_bmi

array([31.86682521, 42.92387325, 30.55555556, 45.3125    , 24.83564646])

In [19]:
t = []

for item in np_bmi:
    if item < 25:
        t.append(item)
        
t
        

[24.835646457268076]

In [20]:
np_bmi[np_bmi<25]

array([24.83564646])

In [21]:
np_bmi < 25

array([False, False, False, False,  True])

In [23]:
np_bmi[np.logical_and(np_bmi>25, np_bmi<40)]

array([31.86682521, 30.55555556])

In [25]:
np_bmi[np.logical_or(np_bmi<15, np_bmi>40)]

array([42.92387325, 45.3125    ])

In [26]:
np_bmi[np.logical_not()]

array([31.86682521, 42.92387325, 30.55555556, 45.3125    , 24.83564646])

- scalar - 42
- vector - [1, 2, 3, 4, 5]
- matrix - [(1,2), (3,4)]
- tensor - [[(2,4)]] czyli macierz wielowymiarowa

In [27]:
data = np.array([[1,2], 
                 [3,4]])

In [28]:
data *5 

array([[ 5, 10],
       [15, 20]])

In [29]:
data * data

array([[ 1,  4],
       [ 9, 16]])

In [30]:
data * np.array([42, 42])

array([[ 42,  84],
       [126, 168]])

In [31]:
data


array([[1, 2],
       [3, 4]])

In [32]:
data[1]

array([3, 4])

In [34]:
data[0:2, 0]

array([1, 3])

In [36]:
y = np.arange(10)

In [43]:
np.array(y*item for item in range(10))

array(<generator object <genexpr> at 0x7f4d41811620>, dtype=object)

In [42]:
x


array(<generator object <genexpr> at 0x7f4d41811310>, dtype=object)

In [45]:
result = np.array([[y * x for y in np.arange(1, 11)] for x in np.arange(1,11)])
result

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [48]:
result[0,0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
result[0:, 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
result[0::2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90]])

In [54]:
result[1::2]

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [55]:
result[0::2, 0::2]

array([[ 1,  3,  5,  7,  9],
       [ 3,  9, 15, 21, 27],
       [ 5, 15, 25, 35, 45],
       [ 7, 21, 35, 49, 63],
       [ 9, 27, 45, 63, 81]])

In [57]:
result[[1, 5, 7]]

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80]])

In [60]:
result[[1, 2, 3]]

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40]])

In [62]:
result[[1, 2, 3], ::2]

array([[ 2,  6, 10, 14, 18],
       [ 3,  9, 15, 21, 27],
       [ 4, 12, 20, 28, 36]])

In [63]:
result

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [66]:
result[result % 2 == 0] = False

In [67]:
result

array([[ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  0,  9,  0, 15,  0, 21,  0, 27,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0, 15,  0, 25,  0, 35,  0, 45,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  0, 21,  0, 35,  0, 49,  0, 63,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  0, 27,  0, 45,  0, 63,  0, 81,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [70]:
result[result % 2 == 0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
result[result % 2 == 0].reshape(5, -1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])